AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'This templates enables AWS Config.'
Parameters:
  DeliveryChannelExists:
    Type: String
    Description: 'Do you have an exisiting AWS Config delivery channel?'
    Default: 'false'
    AllowedValues: ['false', 'true']
  lambdaFunctionName:
    Type: "String"
    AllowedPattern: "^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$"
    Default: "t3chfest-awsconfig"
Conditions:
  CreateDeliveryChannel: !Equals [ !Ref DeliveryChannelExists, 'false' ]
Resources:
  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      Name: t3chfest
      RecordingGroup:
        ResourceTypes: ['AWS::EC2::SecurityGroup','AWS::S3::Bucket','AWS::S3::AccountPublicAccessBlock','AWS::IAM::User']
      RoleARN: !GetAtt [ConfigRole, Arn]
  DeliveryChannel:
    Condition: CreateDeliveryChannel
    Type: AWS::Config::DeliveryChannel
    Properties:
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: Six_Hours
      S3BucketName: !Ref 'ConfigBucket'
  ConfigBucket:
    Type: AWS::S3::Bucket
  ConfigRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: [config.amazonaws.com]
          Action: ['sts:AssumeRole']
      ManagedPolicyArns: ['arn:aws:iam::aws:policy/service-role/AWSConfigRole']
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: s3:GetBucketAcl
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'ConfigBucket']]
          - Effect: Allow
            Action: s3:PutObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'ConfigBucket', /AWSLogs/,
                !Ref 'AWS::AccountId', /*]]
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Effect: Allow
            Action: config:Put*
            Resource: '*'
  ConfigRuleS3read:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: S3PublicRead
      Description: S3 public read
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_READ_PROHIBITED
  ConfigRuleS3write:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: S3PublicWrite
      Description: S3 public write
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_WRITE_PROHIBITED
  ConfigRuleSSHrestricted:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: EC2SecurityGroupssh
      Description: EC2 SecurityvGroup ssh open
      Source:
        Owner: AWS
        SourceIdentifier: INCOMING_SSH_DISABLED
  ConfigRuleIAMUser:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: MFAUserEnabled
      Description: IAM User MFA enabled
      Source:
        Owner: AWS
        SourceIdentifier: IAM_USER_MFA_ENABLED
      MaximumExecutionFrequency: Three_Hours
  lambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: "AWS Config Remediation Code"
      FunctionName: !Ref "lambdaFunctionName"
      Code:
        ZipFile: !Sub |
          import json
          import boto3
          import os
          from botocore.exceptions import ClientError
          ec2 = boto3.client('ec2')

          def handler(event,context):
              #Creating delete request
              print('se invoca')
              print(event)
              dtype = event['detail-type']
              if dtype == "Config Rules Compliance Change":
                  ruleName = event['detail']['configRuleName']
                  if ruleName == "EC2SecurityGroupssh":
                      status = event['detail']['newEvaluationResult']['complianceType']
                      if status == "NON_COMPLIANT":
                          nonCompliantSG = event['detail']['newEvaluationResult']['evaluationResultIdentifier']['evaluationResultQualifier']['resourceId']
                          try:
                              remediate_sg('0.0.0.0/0', nonCompliantSG)
                          except ClientError as e:
                              print(e)
                  elif ruleName == "MFAUserEnabled":
                      status = event['detail']['newEvaluationResult']['complianceType']
                      userId = event['detail']['newEvaluationResult']['evaluationResultIdentifier']['evaluationResultQualifier']['resourceId']
                      attach_detach_RestrictivePolicy(userId,status)
                  elif ruleName == "S3PublicRead" or "S3PublicWrite":
                      status = event['detail']['newEvaluationResult']['complianceType']
                      if status == "NON_COMPLIANT":
                          nonCompliantBucket = event['detail']['newEvaluationResult']['evaluationResultIdentifier']['evaluationResultQualifier']['resourceId']
                          s3 = boto3.resource('s3')
                          bucket = s3.Bucket(nonCompliantBucket)
                          acl = bucket.Acl()
                          acl.put(ACL='private')
          def remediate_sg(ip, sg):
              """Return EC2 SG object based on filters defined by provided VPCID/SGID"""
              sgrules = ec2.describe_security_groups(Filters=[
                  {
                      'Name': 'group-id',
                      'Values': [sg]
                  }
              ]
              )
              r = remove_old_rule(sgrules, sg, ip)

          def remove_old_rule(r, sg, ip):
              """Remove any existing rules in the SG provided the current CIDR doesn't match"""
              rules = r['SecurityGroups'][0]
              if len(rules['IpPermissions']) > 0:
                  for rule in rules['IpPermissions']:
                      port = rule['FromPort']
                      if port == 22:
                          curr_ip = rule['IpRanges'][0]['CidrIp']
                          if str(ip) == str(curr_ip):
                              print('revoca')
                              ec2.revoke_security_group_ingress(GroupId=sg, IpPermissions=[rule])
                              return True
              else:
                  print('No security group rules for ' + sg)
                  return True

          def attach_detach_RestrictivePolicy(userId,status):
              iam = boto3.resource('iam')
              client = boto3.client('iam')
              paginator = client.get_paginator('list_users')
              response_iterator = paginator.paginate()
              NON_COMPLIANT_USER = ""
              for r in response_iterator:
                  for u in r['Users']:
                      user = iam.User(u['UserName'])
                      user_id = user.user_id
                      if userId == user_id:
                          NON_COMPLIANT_USER =  user
                          break
              if status == "NON_COMPLIANT":
                  response = NON_COMPLIANT_USER.attach_policy(
                      PolicyArn=os.environ['PolicyARN']
                  )
              else:
                  response = NON_COMPLIANT_USER.detach_policy(
                      PolicyArn=os.environ['PolicyARN']
                  )
      Handler: "index.handler"
      Role: !GetAtt "lambdaIAMRole.Arn"
      Runtime: "python3.7"
      Environment:
        Variables:
          PolicyARN: !Ref ForceMFA
  lambdaIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Resource: "*"
                Action:
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:RevokeSecurityGroupIngress"
                  - "iam:ListUsers"
                  - "iam:GetUser"
                  - "iam:AttachUserPolicy"
                  - "iam:DetachUserPolicy"
              - Effect: "Allow"
                Resource: "*"
                Action:
                  - "s3:PutBucketAcl"
              - Effect: "Allow"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${lambdaFunctionName}:*"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
          PolicyName: "AwsConfigRemediation_Lambda_Policy"
  lambdaLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/${lambdaFunctionName}"
      RetentionInDays: 90
  AmazonCloudWatchEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.config
        detail-type:
          - 'Config Rules Compliance Change'
      Targets:
        -
          Arn: !GetAtt lambdaFunction.Arn
          Id: LambdaConfigEvent
  ForceMFA:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowAllUsersToListAccounts"
            Effect: "Allow"
            Action:
              - "iam:ListAccountAliases"
              - "iam:ListUsers"
            Resource: !Sub "arn:aws:iam::${AWS::AccountId}:user/*"
          - Sid: "AllowIndividualUserToSeeTheirAccountInformation"
            Effect: "Allow"
            Action:
              - "iam:ChangePassword"
              - "iam:CreateLoginProfile"
              - "iam:DeleteLoginProfile"
              - "iam:GetAccountPasswordPolicy"
              - "iam:GetAccountSummary"
              - "iam:GetLoginProfile"
              - "iam:UpdateLoginProfile"
            Resource:
              Fn::Join:
                - ""
                - - !Sub "arn:aws:iam::${AWS::AccountId}:user"
                  - "/${aws:username}"
          - Sid: "AllowIndividualUserToListTheirMFA"
            Effect: "Allow"
            Action:
              - "iam:ListVirtualMFADevices"
              - "iam:ListMFADevices"
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:mfa/*"
              - Fn::Join:
                  - ""
                  - - !Sub "arn:aws:iam::${AWS::AccountId}"
                    - ":user/${aws:username}"
          - Sid: "AllowIndividualUserToManageThierMFA"
            Effect: "Allow"
            Action:
              - "iam:CreateVirtualMFADevice"
              - "iam:DeactivateMFADevice"
              - "iam:DeleteVirtualMFADevice"
              - "iam:EnableMFADevice"
              - "iam:ResyncMFADevice"
            Resource:
              - Fn::Join:
                  - ""
                  - - !Sub "arn:aws:iam::${AWS::AccountId}"
                    - ":mfa/${aws:username}"
              - Fn::Join:
                  - ""
                  - - !Sub "arn:aws:iam::${AWS::AccountId}"
                    - ":user/${aws:username}"
          - Sid: "DoNotAllowAnythingOtherThanAboveUnlessMFAd"
            Effect: "Deny"
            NotAction: "iam:*"
            Resource: "*"
